### ISSUE TITLE
Question about L_uniform

### ISSUE THREAD

**Issue by zhangdan8962** [SsnL/moco#1]
Hi,

I realized that when you calculate the L_uniform with intra-batch, you included the pair distances from q. I am wondering why you did not use the distance between q and negative k?

Thank you in advance for the help!

**Comment by ssnl** [comment]
You can surely use that too. I did not because 
(1) the queue is already very large so adding more terms to the estimate will likely not help much,
(2) including pairwise q distance is rather cheap, and gives better gradient signal (since gradient flows back from both sides of the distance, unlike |q-k| or |q-queue|).
(3) computation is already not very fast.

Feel free to reopen this issue if this doesn't answer your question!
